nama = input("Nama                      : ")
nim =  input("NIM                       : ")
paralel = input("Kelas Paralel             : ")
ttl = input("Tempat/Tanggal Lahir      : ")
alamat = input("Alamat                    : ")
hobby = input("Hobby                     : ")
nomor_handphone =input("No. HP                    : ")

print()
print("Nama                      :" + nama)
print("NIM                       :" + nim)
print("Kelas Paralel             :" + paralel)
print("Tempat/Tanggal Lahir      :" + ttl)
print("Alamat                    :" + alamat)
print("Hobby                     :" + hobby)
print("No. HP                    :" + nomor_handphone)